### PR TITLE
Fix 643265 in the silliest possible way.

### PR DESCRIPTION
**Pull request by ericlaw1979**
Workaround suggested by https://bugs.chromium.org/p/chromium/issues/detail?id=643265#c6

### CODE REVIEW

**Comment by evanstade** [comment]
thanks for the patch! Can we do this in a less silly way? i.e. don't add ?? in the first place but instead morph the command at that point? I'm worried that making lots of silly changes over time leads to code that's more byzantine and surprising than it has to be.

**Comment by ericlaw1979** [comment]
Alas, if I understood how to fix this properly, I would have done so. :-/ Since the bug has been active for seven months, my assumption is that it's not trivial even for those who understand the code.

**Comment by ericlaw1979** [comment]
Okay, this _seems_ to work. It occurs to me that I may be committing to the wrong branch (gh-pages vs. master?) though?

**Comment by evanstade** [comment]
cleaning up old PRs. I can't remember what happened here, but it seems the functionality was added in c776d241a3eb8358a5c6d478d5eabf51066eaccf

thanks again for the contribution.

**Pull request closed without merging**
